@startuml
hide circle
skinparam classAttributeIconSize 0
title Vista de processo nível 1

participant ":HTTP Client" as Client
participant ":LMS" as System

' Criação de autor
Client -> System: POST /authors
alt success
    System --> Client: 1.1: 201 Created (Autor criado)
else error
    System --> Client: 1.2: 400 Bad Request (Erro de validação)
end




@enduml
