@startuml
' Definindo os participantes
participant "HTTP Client" as client
participant "reader[0] : Reader" as reader0
participant "reader[1] : Reader" as reader1
participant "Message Broker" as mb

' O cliente faz uma requisição para criar um novo leitor
client o-> reader0: POST /readers {readerData, photo}
activate reader0

' O Reader Service valida o token e permissões localmente
reader0 -> reader0: Validar token JWT e permissões

' Verifica as permissões e cria o leitor
reader0 -> reader0: save(readerData, photo)

reader0 -> mb: publish(readerCreated)

' Replicando dados para a outra instância (espelhamento)
mb -> reader1: notify(readerCreated)
activate reader1
reader1 -> reader1: save(reader)


' Responder ao cliente com sucesso final após a replicação


reader0 -->o client: 201 Created
deactivate reader1
deactivate reader0
@enduml
